apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: navidrome

resources:
  - ../../base

# Use Longhorn storage class for navidrome data PVC
patches:
  - target:
      kind: PersistentVolumeClaim
      name: navidrome-data-pvc
    patch: |-
      - op: add
        path: /spec/storageClassName
        value: longhorn
