apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: navidrome

resources:
  - namespace.yaml
  - service-accounts.yaml
  - pvcs.yaml
  - music-pvc.yaml
  - deployment.yaml
  - httproute.yaml

labels:
  - pairs:
      app.kubernetes.io/part-of: navidrome
    includeSelectors: false

images:
  - name: deluan/navidrome
    newTag: "0.53.3"
